- CHANGELOG.md
- examples/main.rs
- src/lib.rs
> Change `on_message` callback into a trait

- CHANGELOG.md
- examples/main.rs
- src/lib.rs
- src/peer.rs
- src/transport.rs
The transport shall verify the header ID against the source address
See #69
> Add listen_address to override public_address used in header

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/transport/encoding/raptorq_encoder.rs
> Add the auto prune of expired items in RaptorQ cache

- CHANGELOG.md
- Cargo.toml
- src/handling.rs
- src/lib.rs
- src/mantainer.rs
- src/transport.rs
- Drop the RWLockGuard as soon as possible
- Improve logs
- Bump version to 0.3.0-rc.0
Resolves #80
> Fix deadlock on RWLock

- CHANGELOG.md
- Cargo.toml
- src/handling.rs
- src/lib.rs
- src/transport.rs
- src/transport/encoding/raptorq/encoder.rs
- src/transport/sockets.rs
- Add configuration to set an interval between each UDP send
- Add configuration to choose the RaptorQ FEC redundancy factor
Resolves #82
Resolves #83
> Add `send interval` and `FEC redundancy` configuration

- .github/workflows/build.yml
- Cargo.toml
- src/handling.rs
- src/transport.rs
- src/transport/encoding/raptorq/decoder.rs
- src/transport/sockets.rs
- tests/lib.rs
In addition to test harness, other minor improvements are added
- Add UDP send retry conf
- Preserve propagation in some edge-corner cases
Resolves #27
> Add test-harness

- CHANGELOG.md
- Cargo.toml
- src/handling.rs
- src/transport.rs
- src/transport/encoding/raptorq.rs
- src/transport/encoding/raptorq/encoder.rs
- src/transport/sockets.rs
- tests/lib.rs
- Add `udp_send_retry_interval_millis` param
- Add `udp_recv_buffer_size` param
Other minor improvements
Resolves #86
> Add UDP network configuration

- CHANGELOG.md
- Cargo.toml
- src/encoding.rs
- src/encoding/payload/nodes.rs
> Fix empty payload NodesMessage decoding

- CHANGELOG.md
- src/handling.rs
- src/lib.rs
- src/transport.rs
> Handle and try to decode chunks in a separate tokio task

- CHANGELOG.md
- Cargo.toml
- examples/main.rs
- src/config.rs
- src/handling.rs
- src/kbucket.rs
- src/kbucket/bucket.rs
- src/lib.rs
- src/peer.rs
- src/transport.rs
- src/transport/encoding.rs
- src/transport/encoding/plain_encoder.rs
- src/transport/encoding/raptorq.rs
- src/transport/encoding/raptorq/decoder.rs
- src/transport/encoding/raptorq/encoder.rs
- src/transport/sockets.rs
- tests/lib.rs
> Kadcast serde Config

- CHANGELOG.md
- Cargo.toml
- src/mantainer.rs
- tests/lib.rs
Perform a peer bootstrap even if started before his bootstrapping nodes
Resolves #97
> Implement a safe bootstrap

- CHANGELOG.md
- Cargo.toml
- src/mantainer.rs
Bump to 0.4.0-rc.2
Resolves #99
> Retry on dns failure

- CHANGELOG.md
- Cargo.toml
- src/transport/encoding/raptorq/decoder.rs
Fix dupemap cache
Resolves #101
> Fix dupemap cache

- CHANGELOG.md
- Cargo.toml
- src/kbucket.rs
- src/kbucket/bucket.rs
- src/lib.rs
- tests/lib.rs
> Return a set of random active nodes

- .github/workflows/build.yml
- CHANGELOG.md
- src/encoding/payload/nodes.rs
- src/kbucket.rs
- src/kbucket/bucket.rs
- src/mantainer.rs
> Remove idle nodes

- CHANGELOG.md
- src/encoding.rs
- src/handling.rs
- src/kbucket.rs
- src/kbucket/bucket.rs
- src/kbucket/key.rs
- src/lib.rs
- src/peer.rs
- src/transport/encoding/raptorq.rs
- src/transport/encoding/raptorq/decoder.rs
- tests/lib.rs
> Use provided nonce instead of regenerate it

- CHANGELOG.md
- src/lib.rs
- src/mantainer.rs
Refactor `TableMantainer` to not forget about bootstrapping nodes
Resolves #112
> Bootstrappers discovery while maintenance

- CHANGELOG.md
- Cargo.toml
- Remove idle nodes during bucket mantainance #108
- Use provided nonce instead of regenerate #110
- Network bootstrap after being disconnected #112
Full CHANGELOG here https://github.com/dusk-network/kadcast/compare/v0.4.0...v0.4.1
> Release 0.4.1

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/rwlock.rs
> Add diagnostics feature flag to RwLock

- CHANGELOG.md
- src/encoding/header.rs
- src/kbucket/key.rs
> Change `BinaryID::from_nonce` to return result

- CHANGELOG.md
- Cargo.toml
- src/config.rs
- src/encoding.rs
- src/encoding/header.rs
- src/encoding/message.rs
- src/handling.rs
- src/kbucket.rs
- src/kbucket/bucket.rs
- src/lib.rs
- src/maintainer.rs
- tests/lib.rs
See also dusk-network/rusk#2197
> Add versioning for network peers

- CHANGELOG.md
- Cargo.toml
- src/encoding.rs
- src/encoding/message.rs
- src/encoding/payload/broadcast.rs
- src/handling.rs
- src/lib.rs
- src/transport.rs
- src/transport/encoding/raptorq.md
- src/transport/encoding/raptorq.rs
- src/transport/encoding/raptorq/decoder.rs
- src/transport/encoding/raptorq/encoder.rs
- tests/lib.rs
```
Sep 28 12:31:41.750 DEBUG kadcast::transport::encoding::raptorq::encoder: event="Start encoding payload" ray="f94a1fa9b9348bcc1dc273443fcfd1a5c334b495aaa41aad3593842df9bf7d74" encode_info="00000186a000051001000108"
Sep 28 12:31:41.752 DEBUG kadcast::transport::encoding::raptorq::encoder: event="Start encoding payload" ray="f94a1fa9b9348bcc1dc273443fcfd1a5c334b495aaa41aad3593842df9bf7d74" encode_info="00000186a000051001000108"
Sep 28 12:31:41.753 DEBUG kadcast::transport::encoding::raptorq::encoder: event="Start encoding payload" ray="f94a1fa9b9348bcc1dc273443fcfd1a5c334b495aaa41aad3593842df9bf7d74" encode_info="00000186a000051001000108"
Sep 28 12:31:41.754 DEBUG kadcast::transport::encoding::raptorq::encoder: event="Start encoding payload" …
```
> Add Ray-ID for message tracking
